# Generated by Django 3.0.2 on 2020-07-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('ligand', '0014_chemblassays_cell_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assayexperiment',
            old_name='protein',
            new_name='receptor',
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='activity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='cell_line',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='chembl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='document_chembl_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Publication'),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='smiles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='assay_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='assay_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_relation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_units',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='assayexperiment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='assay',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='published_relation',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='published_type',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='published_units',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='published_value',
        ),
    ]
