# Generated by Django 3.0.2 on 2020-07-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0015_auto_20200713_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemblassays',
            name='skip',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
