# Generated by Django 3.0.2 on 2020-07-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0016_chemblassays_skip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemblassays',
            name='skip',
        ),
    ]
